conn = new Mongo();
db = conn.getDB("baches");

db.usuarios.insert([
   { _id:       1, 
     nombres:   'Juan Jose',
     apellidos: 'Salas Contreras',
     telefono:  345423,
     celular:   956627263,
     ciudad:    'Arequipa',
     contrasenia:'SalasC',
     direccion: 'Av. EE.UU. E-23',
     email:     'jSalas@hotmail.com',
     tarjeta:[{
      _id:1,
      nro:6234243445612345,
      fec_exp: '2020-02-20',
      cod_seg: '345',
      clave: '5644'
      },],
   },
    { _id:       2, 
     nombres:   'Hernan Luis',
     apellidos: 'Gomez Gutierres',
     telefono:  334576,
     celular:   963548798,
     ciudad:    'Arequipa',
     contrasenia:'HLuis',
     direccion: 'Pedro Diez Canseco A-9',
     email:     'hgomez@hotmail.com',
      tarjeta:[{
      _id:1,
      nro:1434456444412345,
      fec_exp: '2020-02-20',
      cod_seg: '345',
      clave: '5644'
      },], 
   },
    { _id:       3, 
     nombres:   'Pedro Saul',
     apellidos: 'Vargaz Torres',
     telefono:  457848,
     celular:   978956485,
     ciudad:    'Arequipa',
     contrasenia:'PedroS',
     direccion: 'Calle los Cedros B-2',
     email:     'pvargaz@hotmail.com',
      tarjeta:[{
      _id:1,
      nro:1111243445612345,
      fec_exp: '2020-02-20',
      cod_seg: '345',
      clave: '5644'
      },], 
   },
    { _id:       4, 
     nombres:   'Cesar Jhair',
     apellidos: 'Quispe Mamani',
     telefono:  524869,
     celular:   915487569,
     ciudad:    'Arequipa',
     contrasenia:'CesarJ',
     direccion: 'Av. Aviacion J-16',
     email:     'cquispe@hotmail.com',
      tarjeta:[{
      _id:1,
      nro:6299993445612345,
      fec_exp: '2020-02-20',
      cod_seg: '345',
      clave: '5644'
      },], 
   },
    { _id:       5, 
     nombres:   'Julio Esteban',
     apellidos: 'Cisneros Cuevas',
     telefono:  124578,
     celular:   915648596,
     ciudad:    'Arequipa',
     contrasenia:'JulioE',
     direccion: 'Calle Brasil P-19',
     email:     'jcisneros@hotmail.com',
      tarjeta:[{
      _id:1,
      nro:7846659847365452,
      fec_exp: '2020-02-20',
      cod_seg: '345',
      clave: '5644'
      },], 
   }   
]);

db.anuncios.insert([
  {_id:1,
    _id_usu:1,
    titulo:'Vendo Auto a precio rasonable',
    descripcion:'Estoy en busqueda de alguna persona que desee comprar mi auto el cual se encuentra en gran estado si te interesa llamame y te doy detalles',
    fec_publicacion:'2017-01-02',
    estado:'Disponible',
    precio:8000,
    categorias:[{1:1}],
    marca:'Nissan',
    kilometraje:123456,
    transmision:'Automatica',
    destacado:{ porcentaje:100,
                fecha:'2017-01-02'},
  },
  {_id:2,
    _id_usu:2,
    titulo:'Vendo Moto a buen precio',
    descripcion:'Si te gustan mi moto puedes contactarme y te dare los detalles que desees',
    fec_publicacion:'2017-02-03',
    estado:'Disponible',
    precio:3000,
    categorias:[{1:2}],
    marca:'Honda',
    kilometraje:102303,
  },
  {_id:3,
    _id_usu:3,
    titulo:'Vendo Camion en buen estado',
    descripcion:'Si te interesa puedes llamarme y podria rebajarte el precio del anuncio',
    fec_publicacion:'2017-02-07',
    estado:'Disponible',
    precio:30000,
    categorias:[{1:3}],
    marca:'Volvo',
    kilometraje:093202,
  },
  {_id:4,
    _id_usu:4,
    titulo:'Vendo Departamento a precio rasonable',
    descripcion:'Si deseas adquirir este hermoso departamento comunicate conmigo',
    fec_publicacion:'2017-01-10',
    estado:'Disponible',
    precio:20000,
    categorias:[{2:1}],
    metros_cuadrados:90,
    ubicacion:'Av. Aviacion',
    destacado:{ porcentaje:50,
                fecha:'2017-01-10'},
  },
  {_id:5,
    _id_usu:5,
    titulo:'Vendo Casa',
    descripcion:'Vendo casa muy hermosa y muy bien ubicada',
    fec_publicacion:'2017-02-20',
    estado:'Disponible',
    precio:45000,
    categorias:[{2:2}],
    metros_cuadrados:120,
    pisos:2,
    ubicacion:'Calle Peru E-5',
  },
  {_id:6,
    _id_usu:1,
    titulo:'Vendo terreno en buena zona',
    descripcion:'Si necesitas un terreno grande y bien ubicado llamame',
    fec_publicacion:'2017-02-30',
    estado:'Cancelado',
    precio:2000,
    categorias:[{2:3}],
    metros_cuadrados:100,
    ubicacion:'Calle Esmeraldas',
  },
  {_id:7,
    _id_usu:2,
    titulo:'Vendo Licuadora en buen estado',
    descripcion:'Mandame un whatsapp si estas interesado',
    fec_publicacion:'2017-02-08',
    estado:'Disponible',
    precio:100,
    categorias:[{3:1}],
  },
  {_id:8,
    _id_usu:3,
    titulo:'Vendo Hermosos Muebles',
    descripcion:'Estos muebles combinaran con cualquier tapisado asi que llamame si no quieres perderlos',
    fec_publicacion:'2017-02-01',
    estado:'Vendido',
    precio:1500,
    categorias:[{3:2}],
    destacado:{ porcentaje:75,
                fecha:'2017-02-01'},
  },
  {_id:9,
    _id_usu:4,
    titulo:'Vendo Sapolio Desinfectante',
    descripcion:'Vendo Sapolio Desinfectante pino frasco 3785 ml si quieres uno o varios contactame',
    fec_publicacion:'2017-01-28',
    estado:'Disponible',
    precio:10,
    categorias:[{4:1}],
  },
  {_id:10,
    _id_usu:5,
    titulo:'Reloj Analógico de Pared',
    descripcion:'Vendo este hermoso Reloj Analógico de Pared con Diseño Espejo Amor-Plata',
    fec_publicacion:'2017-02-10',
    estado:'Disponible',
    precio:97,
    categorias:[{4:2}],
  },
  {_id:11,
    _id_usu:1,
    titulo:'Vendo MagiDeal Portátiles',
    descripcion:'Vendo genial MagiDeal Portátiles Inoxidable con Tenedores Cucharas Vajilla Palillo 12pcs Kit De Cubiertos',
    fec_publicacion:'2017-02-30',
    estado:'Disponible',
    precio:85,
    categorias:[{4:3}],
  },
  {_id:12,
    _id_usu:2,
    titulo:'NUEVO COMPLEJO ARTICULAR CONDROESTIMULADOR',
    descripcion:'Para deportistas que necesitan un suplemento eficaz con el objetivo de minimizar las lesiones y potenciar una recuperación acelerada.',
    fec_publicacion:'2017-03-16',
    estado:'Disponible',
    precio:39,
    categorias:[{4:4}],
    destacado:{ porcentaje:25,
                fecha:'2017-03-16'},
  },
  {_id:13,
    _id_usu:3,
    titulo:'Vendo gatos angora',
    descripcion:'Si deseas comprar estos hermosos gatitos contactame.',
    fec_publicacion:'2017-01-02',
    estado:'Disponible',
    precio:30,
    categorias:[{5:1}],
  },
  {_id:14,
    _id_usu:4,
    titulo:'Vendo cachorros pitbulls',
    descripcion:'Vendo estos hermosos cachorros pitbulls a buen precio',
    fec_publicacion:'2017-02-11',
    estado:'Disponible',
    precio:120,
    categorias:[{5:2}],
  },
  {_id:15,
    _id_usu:5,
    titulo:'Vendo conejos Cabeza de leon',
    descripcion:'Vendo estos hermosos conejos que pueden ser tus mascotas ahora mismo.',
    fec_publicacion:'2017-02-22',
    estado:'Disponible',
    precio:100,
    categorias:[{5:3}],
  },
  {_id:16,
    _id_usu:1,
    titulo:'Vendo Geniales Hamsters',
    descripcion:'Si necesitas estos pequeños amiguitos en tu hogar puedes contactarme.',
    fec_publicacion:'2017-03-10',
    estado:'Disponible',
    precio:20,
    categorias:[{5:4}],
  },
  {_id:17,
    _id_usu:2,
    titulo:'Reparo Impresoras a domicilio',
    descripcion:'Tengo mucha experiencia en el campo y puedo resolver cualquier problema con impresoras.',
    fec_publicacion:'2017-03-12',
    estado:'Disponible',
    disponibilidad:'Inmediata',
    categorias:[{6:1}],
  },
  {_id:18,
    _id_usu:3,
    titulo:'Clases de matematica a domicilio',
    descripcion:'Doy clases particulares a buen precio y tengo mucha experiencia en el campo',
    fec_publicacion:'2017-02-18', 
    estado:'Disponible',
    disponibilidad:'Fines de semana',
    categorias:[{6:2}],
  },
  {_id:19,
    _id_usu:4,
    titulo:'Limpieza de vidrios especializada para empresas',
    descripcion:'Otorgo servicios de limpieza para diversos locales en el sector si estas interesado contactame',
    fec_publicacion:'2017-02-05',
    estado:'Disponible',
    disponibilidad:'Inmediata',
    categorias:[{6:3}],
  },
  {_id:20,
    _id_usu:5,
    titulo:'Decoraciones Geniales para tu hogar',
    descripcion:'Somos expertos en el campo, si necesitas que decoren tu hogar llamanos',
    fec_publicacion:'2017-03-17',
    estado:'Disponible',
    disponibilidad:'Dias entre semana',
    categorias:[{6:4}],
  },
  {_id:21,
    _id_usu:1,
    titulo:'Vendo Moto X a buen precio',
    descripcion:'Vendo Moto X casi nuevo a un gran precio conversable',
    fec_publicacion:'2017-03-22',
    estado:'Disponible',
    precio:120,
    categorias:[{7:1}],
    destacado:{ porcentaje:100,
                fecha:'2017-03-22'},
  },
  {_id:22,
    _id_usu:2,
    titulo:'Vendo Tablet Mini',
    descripcion:'Vendo Tablet Mini estado 9 de 10',
    fec_publicacion:'2017-02-06', 
    estado:'Disponible',
    precio:130,
    categorias:[{7:2}],
  },
  {_id:23,
    _id_usu:3,
    titulo:'Vendo PC-Gamer',
    descripcion:'Vendo PC-Gamer casi nueva si te interesa mandame un whatsapp',
    fec_publicacion:'2017-02-14',
    estado:'Disponible',
    precio:2500,
    categorias:[{7:3}],
  },
  {_id:24,
    _id_usu:4,
    titulo:'Vendo Laptop de sexta generacion',
    descripcion:'Vendo laptop Accer en muy buen estado perfecta para trabajo',
    fec_publicacion:'2017-04-01',
    estado:'Vendido',
    precio:1500,
    categorias:[{7:4}],
  },
  {_id:25,
    _id_usu:5,
    titulo:'Vendo Camara semiprofesional',
    descripcion:'Genial camara de 32 mega pixeles que puede ser tuya si me llamas ahora',
    fec_publicacion:'2017-04-03',
    estado:'Disponible',
    precio:1200,
    categorias:[{7:5}],
    destacado:{ porcentaje:100,
                fecha:'2017-04-03'},
   },
]);

db.categorias.insert([
  { _id: 1,
    nombre: "Vehiculo",
    subcategorias:[
                    { _id:1,
                      nombre:"Autos"
                    },
                    { _id:2,
                      nombre:"Motos"
                    },
                    { _id:3,
                      nombre:"Camiones"
                    }
                  ]
  },
  { _id: 2,
    nombre: "Inmuebles",
    subcategorias:[
                    { _id:1,
                      nombre:"Departamentos"
                    },
                    { _id:2,
                      nombre:"Casas"
                    },
                    { _id:3,
                      nombre:"Terrenos"
                    }
                  ]
  },
  { _id: 3,
    nombre: "Hogar",
    subcategorias:[
                    { _id:1,
                      nombre:"Electrodomesticos"
                    },
                    { _id:2,
                      nombre:"Muebles"
                    }
                  ]
  },
  { _id: 4,
    nombre: "Productos",
    subcategorias:[
                    { _id:1,
                      nombre:"Limpieza"
                    },
                    { _id:2,
                      nombre:"Decoracion"
                    },
                    { _id:3,
                      nombre:"Cocina"
                    },
                    { _id:4,
                      nombre:"Salud"
                    }
                  ]
  },
  { _id: 5,
    nombre: "Animales",
    subcategorias:[
                    { _id:1,
                      nombre:"Gatos"
                    },
                    { _id:2,
                      nombre:"Perros"
                    },
                    { _id:3,
                      nombre:"Conejos"
                    },
                    { _id:4,
                      nombre:"Hamsters"
                    }
                  ]
  },
  { _id: 6,
    nombre: "Servicios",
    subcategorias:[
                    { _id:1,
                      nombre:"Tecnico"
                    },
                    { _id:2,
                      nombre:"Educacion"
                    },
                    { _id:3,
                      nombre:"Limpieza"
                    },
                    { _id:4,
                      nombre:"Decoracion"
                    }
                  ]
  },
  { _id: 7,
    nombre: "Tecnologia",
    subcategorias:[
                    { _id:1,
                      nombre:"Telefonos"
                    },
                    { _id:2,
                      nombre:"Tablets"
                    },
                    { _id:3,
                      nombre:"Computadoras"
                    },
                    { _id:4,
                      nombre:"Laptops"
                    },
                    { _id:5,
                      nombre:"Camaras"
                    }
                  ]
  }
]);

db.comentarios.insert([
  { anuncio:1,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"es una ganga!",
  },
  { anuncio:1,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"me interesa",
  },
  { anuncio:2,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"es una muy cara!",
  },
  { anuncio:2,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"no estoy seguro :S",
  },
  { anuncio:3,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"es una muy cara!",
    },
  { anuncio:3,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"no estoy seguro :S",
  },
  { anuncio:4,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"se ve grande!",
  },
  { anuncio:4,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"es muy moderno :)",
  },
  { anuncio:5,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"parece una buena opcion!",
  },
  { anuncio:5,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"tal vez lo compre :o",
  },
  { anuncio:6,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"¿Que haria con un terreno tan grande?",
  },
  { anuncio:6,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Se ve muy bien",
  },
  { anuncio:7,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"La necesito",
    },
  { anuncio:7,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Consume mucha elctricidad >:v",
  },
  { anuncio:8,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"El color es perfecto",
  },
  { anuncio:8,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"No me alcanza :(",
  },
  { anuncio:9,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Este es un comentario",
  },
  { anuncio:9,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Este tambien",
  },
  { anuncio:10,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Este es un cometario electrico",
  },
  { anuncio:10,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Este es mecanico",
  },
  { anuncio:11,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Muy importante tener este producto en casa",
  },
  { anuncio:12,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Condroquien?",
  },
  { anuncio:12,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Nani?",
  },
  { anuncio:13,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Para la sopa",
  },
  { anuncio:13,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Para el estofado",
  },
  { anuncio:14,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"rapean?",
  },
  { anuncio:15,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Tambien pueden ser el almuerzo",
    },
  { anuncio:15,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"y cabeza de tigre?",
  },
  { anuncio:16,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"por que son geniales?",
  },
  { anuncio:16,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"por q no? :v",
  },
  { anuncio:17,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Si pluto es un perro y goofy tambien",
    },
  { anuncio:17,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Vienes con impresora?",
  },
  { anuncio:18,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"2 y 2 son 4, 4 y 2 son 6",
  },
  { anuncio:18,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"6 y 2 son 8 y 8, 16",
  },
  { anuncio:19,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Comentario interesante 2: el regreso",
  },
  { anuncio:20,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Y en la ciudad?",
  },
  { anuncio:20,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Si tuviera hogar :,v",
  },
  { anuncio:21,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Se parece mucho al que me robaron",
  },
  { anuncio:22,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Son de las que explotan?",
  },
  { anuncio:22,
    fecha:'2018-01-01',
    usuario:2,
    comentario:"Allahu Akbar!!",
  },
  { anuncio:23,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Nyah Nyah Cthulhu aproves",
  },
  { anuncio:24,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"es Acer >:v",
  },
  { anuncio:25,
    fecha:'2018-01-02',
    usuario:3,
    comentario:"Y toma las fotos sola o por que tan cara?",
  }
]);

db.compras.insert([
  {
    anuncio:8,
    usuario:1,
    fecha:'2018-04-04',
    metodo:'efectivo'
  },
  {
    anuncio:24,
    usuario:5,
    fecha:'2018-04-04',
    metodo:'tarjeta'
  }
]);

db.planes.insert([
  { _id:1,
    porcentaje:25,
    tiempo:30,
    precio: 6
  },
  { _id:2,
    porcentaje:50,
    tiempo:30,
    precio: 12
  },
  { _id:3,
    porcentaje:75,
    tiempo:30,
    precio: 18
  },
  { _id:4,
    porcentaje:100,
    tiempo:30,
    precio: 24
  }
]);
